### ISSUE TITLE
Vertical Scrolling Doesn’t Work

### ISSUE THREAD

**Issue by bokonon-foma** [swiergot/ha-catt-fix#3]
I am casting Dwain’s Dashboard to my Nest Hub using catt.  With ha-catt-fix installed, I cannot scroll the dashboard vertically on my Hub’s screen.  When I uninstall ha-catt-fix scrolling starts working again.  Is this a limitation of the method used to avoid the 10 minute issue?

**Comment by swiergot** [comment]
Thanks for reporting. I can reproduce this and I think I have a fix but need to improve it. Tomorrow I should have something for you to test.

**Comment by swiergot** [comment]
@bokonon-foma Can you please try this and see if it fixes the issue:

https://github.com/swiergot/ha-catt-fix/blob/3-vertical-scrolling-doesnt-work/ha-catt-fix.js

**Comment by bokonon-foma** [comment]
It works!  Thanks so much for this fix and for solving the 10 minute issue.  This is a huge benefit for Home Assistant users.

**Comment by swiergot** [comment]
Happy to help!
