### ISSUE TITLE
Repository structure not compliant for HACS

### ISSUE THREAD

**Issue by TheStork239** [swiergot/ha-catt-fix#4]
The recommended installation route is a custom repository in HACS, but when I try to add a custom repository in HACS it says: “<Integration swiergot/ha-catt-fix> Repository structure for 0.3 is not compliant“

**Comment by swiergot** [comment]
When adding the repository, are you selecting "Lovelace" as category?

**Comment by TheStork239** [comment]
> When adding the repository, are you selecting "Lovelace" as category?

Ah, thanks.  It turned out that when using mobile device browser (Safari in iOS) to access the HA interface, it would not let me select 'Lovelace' so I erroneously thought it would need to be done as an integration.  By using 'old school' desktop computer browser the option to select Lovelace is there and it installed fine.  

So it seems the issue was some HA/HACS UI bug on mobile browsers, rather than anything to do with the ha-catt-fix repository structure.

Thanks for your help.
